# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: azure_packer
  - name: vm_size
    value: "Standard_DS2_V2"

trigger: none 

pool:
  vmImage: ""

stages:
  - stage: Build
    displayName: "Build Packer Image"
    jobs:
